# Generated by Django 4.2.5 on 2024-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_meta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_code",
            field=models.CharField(
                choices=[
                    ("FALL_DETECTED", "Fall Detected"),
                    ("ADD_MEMBER_TO_HOUSE", "New Invite to House"),
                    ("REMOVE_MEMBER_FROM_HOUSE", "Removed from House"),
                    ("UPDATE_HOUSE_METADATA", "House Metadata Updated"),
                    ("INVITE_MEMBER_TO_ROOM", "Invited to Room"),
                ],
                max_length=255,
            ),
        ),
    ]
