# Generated by Django 4.2.5 on 2024-03-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_code",
            field=models.CharField(
                choices=[
                    ("FALL_DETECTED", "Fall Detected"),
                    ("ADD_MEMBER_TO_HOUSE", "New Invite to House"),
                    ("REMOVE_MEMBER_FROM_HOUSE", "Removed from House"),
                    ("UPDATE_HOUSE_METADATA", "House Metadata Updated"),
                    ("UPDATE_ROOM_METADATA", "Update room meta data"),
                    ("INVITE_MEMBER_TO_ROOM", "Invited to Room"),
                ],
                max_length=255,
            ),
        ),
    ]
