# Generated by Django 4.2.5 on 2024-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0004_notification_is_seen_alter_notification_event_code",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_code",
            field=models.CharField(
                choices=[
                    ("FALL_DETECTED", "Fall Detected"),
                    ("ADD_MEMBER_TO_HOUSE", "New Invite to House"),
                    ("REMOVE_MEMBER_FROM_HOUSE", "Removed from House"),
                    ("UPDATE_HOUSE_METADATA", "House Metadata Updated"),
                    ("UPDATE_ROOM_METADATA", "Update room meta data"),
                    ("INVITE_MEMBER_TO_ROOM", "Invited to Room"),
                    ("INVITED_TO_ROOM", "Invited to Room"),
                    ("INVITED_TO_HOUSE", "Invited to House"),
                    ("REMOVED_FROM_ROOM", "Removed from Room"),
                    ("REMOVED_FROM_HOUSE", "Removed from House"),
                    ("NOTIFY_USER_DEVICE_FALL_DETECTED", "Fall Detected"),
                ],
                max_length=255,
            ),
        ),
    ]
