# Generated by Django 4.2.5 on 2024-05-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_alter_devicespec_series_name"),
        ("notification", "0005_alter_notification_event_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="device.device",
            ),
        ),
    ]
