# Generated by Django 4.2.5 on 2024-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_devicespec_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicespec",
            name="series_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
