# Generated by Django 4.2.5 on 2024-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_alter_device_serial_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(max_length=255),
        ),
    ]
